name: bwu_fontawesome_iconset_svg
version: 0.3.0-3
description: FontAwesome SVG icons for core-elements and paper-elements
homepage: https://github.com/bwu-dart/bwu_fontawesome_iconset_svg
authors:
- Günter Zöchbauer <guenter@gzoechbauer.com>
- Kun Zhao <kunzhao77@gmail.com>
environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  polymer: ^1.0.0-rc.10
  polymer_elements: ^1.0.0-rc.2
  reflectable: ^0.5.0
  web_components: ^0.12.0

dev_dependencies:
  archive: '>=1.0.19 <2.0.0'  # for fa_upgrade
  bwu_grinder_tasks: '>=0.1.0 <0.2.0'
  grinder: '>=0.7.2 <0.9.0'
  path: '>=1.3.5 <2.0.0' # for fa_upgrade
  test: '>=0.12.0 <0.13.0'

transformers:
- web_components:
    entry_points:
    - example/example01.html
    - example/example02.html
    - example/example03.html
#    - test/all_icons_test.html
#    - test/simple_test.html

- reflectable:
    entry_points:
    - example/example01.dart
    - example/example02.dart
    - example/example03.dart
#    - test/all_icons_test.dart
#    - test/simple_test.dart

- test/pub_serve:
    $include: test/**_test{.*,}.dart
