name: bwu_fontawesome_iconset_svg
version: 0.0.5
description: FontAwesome SVG icons for core-elements and paper-elements
homepage: https://github.com/bwu-dart/bwu_fontawesome_iconset
author: Günter Zöchbauer <guenter@gzoechbauer.com>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  core_elements: ">=0.1.1 <0.2.0"
  paper_elements: ">=0.1.0+2 <0.2.0"
  polymer:  '>=0.12.0+5 <0.13.0'
transformers:
- polymer:
    entry_points:
    - example/index.html



