name: bwu_fontawesome_iconset_svg
version: 0.2.0
description: FontAwesome SVG icons for core-elements and paper-elements
homepage: https://github.com/bwu-dart/bwu_fontawesome_iconset_svg
authors:
- Günter Zöchbauer <guenter@gzoechbauer.com>
- Kun Zhao <kunzhao77@gmail.com>
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  core_elements: ">=0.6.0 <0.8.0"
  polymer: '>=0.15.0 <0.17.0'

dev_dependencies:
  archive: '>=1.0.19 <2.0.0'  # for fa_upgrade
  bwu_utils_dev: '>=0.1.0-dev.9 <0.2.0'
  grinder: '>=0.7.0 <0.8.0'
  paper_elements: ">=0.6.0 <0.8.0"
  path: '>=1.3.5 <2.0.0' # for fa_upgrade
  test: #'>=0.12.0 <0.13.0'
    git: git@github.com:dart-lang/test.git

transformers:
- polymer:
    entry_points:
    - example/example01.html
    - example/example02.html
    - example/example03.html
    - test/all_icons_test.html
    - test/simple_test.html

- test/pub_serve:
    $include: test/**_test{.*,}.dart
