name: bwu_fontawesome_iconset_svg
version: 0.1.1
description: FontAwesome SVG icons for core-elements and paper-elements
homepage: https://github.com/bwu-dart/bwu_fontawesome_iconset_svg
author: 
- Günter Zöchbauer <guenter@gzoechbauer.com>
- Kun Zhao <kunzhao77@gmail.com>    
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  core_elements: ">=0.2.0 <0.8.0"
  polymer: '>=0.12.0+5 <0.17.0'
dev_dependencies:
  paper_elements: ">=0.1.0+2 <0.8.0"
transformers:
- polymer:
    entry_points:
    - example/example01.html
    - example/example02.html
    - example/example03.html
